# Generated by Django 4.2.7 on 2023-12-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('odontologos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Nombre_Paciente', models.CharField(max_length=200)),
                ('Codigocita', models.PositiveSmallIntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('Nombre_Odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='odontologos.odontologo')),
            ],
        ),
    ]
