# Generated by Django 4.2.7 on 2023-12-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odontologo', models.CharField(max_length=200)),
                ('imagen', models.FileField(upload_to='imagenes_odontologos/')),
            ],
        ),
    ]
